name: E2E Tests
on:
  push:
    branches:
      - develop
      - master
      - ZEN-675-e2e-tests
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn install
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run your tests
        run: PLAYWRIGHT_EXPERIMENTAL_FEATURES=1 playwright test
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report